name: build_package_rock5_debian

on:
  push:
   branches:
      - "2.5-evo"
      - "dev-release"
      - "release"
      - "enterprise"

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-22.04
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 10
          swap-size-mb: 10
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          overprovision-lvm: 'true'
      - name: remove even more
        run: |
          sudo apt-get purge -y \
            '^llvm-.*' \
            'php.*' \
            '^mongodb-.*' \
            '^mysql-.*' \
            azure-cli \
            google-chrome-stable \
            firefox \
            powershell \
            microsoft-edge-stable \
            mono-devel \
            google-cloud-cli \
            dotnet-sdk-8.0 \
            dotnet-sdk-7.0 \
            temurin-21-jdk \
            dotnet-sdk-6.0 \
            temurin-17-jdk \
            temurin-11-jdk \
            gcc-* \
            temurin-* \
            g++-* \
            gfortran-* \
            cpp-* \
            libclang* \
            openjdk-11-jre-headless
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo df -h
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | awk '{printf "%.2f MB \t %s\n", $1/(1024), $2}'
        
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    
             
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Building OpenHD in CHROOT
        run: |
          git clone https://github.com/OpenHD/ChrootCompilationTest /opt/ChrootCompilationTest
          mkdir -p /opt/ChrootCompilationTest/additionalFiles
          git clone https://github.com/OpenHD/OpenHD -b ${{ github.ref_name }} /opt/ChrootCompilationTest/additionalFiles/ --recursive
          echo $CLOUDSMITH_API_KEY > /opt/ChrootCompilationTest/additionalFiles/cloudsmith_api_key.txt
          echo "standard" > /opt/ChrootCompilationTest/additionalFiles/custom.txt
          echo "arm64" > /opt/ChrootCompilationTest/additionalFiles/arch.txt
          echo "ubuntu" > /opt/ChrootCompilationTest/additionalFiles/distro.txt
          echo "focal" > /opt/ChrootCompilationTest/additionalFiles/flavor.txt
          echo "${{ github.ref_name }}" > /opt/ChrootCompilationTest/additionalFiles/repo.txt

          cd /opt/ChrootCompilationTest/
          sudo apt update
          sudo bash install_dep.sh
          sudo bash build.sh nvidia-agx $API_KEY ubuntu focal
